//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserPolls.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InternalDbEntities : DbContext
    {
        public InternalDbEntities()
            : base("name=InternalDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<POLL_Category> POLL_Category { get; set; }
        public virtual DbSet<POLL_Options> POLL_Options { get; set; }
        public virtual DbSet<POLL_Questions> POLL_Questions { get; set; }
        public virtual DbSet<POLL_Results> POLL_Results { get; set; }
        public virtual DbSet<POLL_Subscription> POLL_Subscription { get; set; }
        public virtual DbSet<POLL_Types> POLL_Types { get; set; }
    
        public virtual ObjectResult<SP_GetOpenQUestions_Result> SP_GetOpenQUestions()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetOpenQUestions_Result>("SP_GetOpenQUestions");
        }
    }
}
