//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserPolls.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLL_Options
    {
        public int AnswerID { get; set; }
        public int PollID { get; set; }
        public string AnesDescription { get; set; }
    }
}
